/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.lib;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test void testSomeLibraryMethod() {
        Library library = new Library();
        assertTrue(library.plugh(), "library.plugh() should return 'true'");
    }
}
