/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean experiment2() {
        System.out.println("this is an experiment2!");
        return true;
    }
}
