/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.lib;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public boolean exper() {
        System.out.println("this is an exper!");
        return true;
    }
}
