/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.lib;

public class Library {
    public boolean master() {
        System.out.println("library.master() called");
        return true;
    }
}
