name: build

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TOKEN: "${{secrets.ALLREP_TOKEN}}"
      CI: "true"
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "build jar"
        run: ./gradlew
