name: xyzzy

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[no-ci]')"
    env:
      ALLREP_TOKEN: "${{secrets.ALLREP_TOKEN}}"
      TOKEN: "${{secrets.ALLREP_TOKEN}}"
      CI: "true"
    steps:
      - name: "set"
        run: set
